global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "nginx"
    static_configs:
      - targets: ["monitoringdemo_nginx_exporter:9113"]
  
  - job_name: "cadvisor"
    static_configs:
      - targets: ["monitoringdemo_cadvisor:8080"]